/*
Shader generated by Savvy - The Smart Shader Cross Compiler.
Author: Apostol Dadachev
Version: 1.0
*/

#version 450 core
layout(binding=0) uniform sampler2D DiffuseTexture;

layout(location=0) in vec3 Normal; /* Original Semantic: NORMAL */
layout(location=1) in vec3 LightDir; /* Original Semantic: LIGHTDIR */
layout(location=2) in vec4 Color; /* Original Semantic: COLOR */
layout(location=3) in vec2 TexCoord; /* Original Semantic: TEXCOORD */
layout(location=4) in vec4 Position; /* Original Semantic: SV_Position */

layout(location=0) out vec4 SavvyOutColor;

void main()
{
	float lightIntensity = clamp(dot(Normal,LightDir), 0.0, 1.0);
	vec4 texColor = texture(DiffuseTexture,TexCoord);
	vec4 finalColor = clamp(Color*texColor*lightIntensity, 0.0, 1.0);
	SavvyOutColor = finalColor;
}
